#install: pod install
podfile: Example/MTCustomAppearance.podspec
#xcode_workspace: Example/MTCustomAppearance.xcworkspace
#xcode_scheme: MTCustomAppearance
#xcode_sdk: iphonesimulator7.0


language: objective-c
osx_image: xcode7.3

script:
  - xctool -workspace Example/MTCustomAppearance.xcworkspace -scheme MTCustomAppearance -sdk iphonesimulator9.3 ONLY_ACTIVE_ARCH=NO
#  - xctool -project Example/MTCustomAppearance.xcworkspace -scheme MTCustomAppearance -sdk iphonesimulator9.0 ONLY_ACTIVE_ARCH=NO
